### ISSUE TITLE
alerts

### ISSUE THREAD

**Issue by Royalgamer06** [MalikAQayum/SteamTracker#7]
Please disable the alerts:
![](https://i.imgur.com/L4CzMXl.png)

**Comment by Royalgamer06** [comment]
Sorry wrong repo!

**Comment by MalikAQayum** [comment]
np, the other steamtracker2 is just something i am working on the side with as i believe if i split the script up in pieces it will be much more readable and easier to maintain.

so i needed to do some alert to see why these shitty async would not abide by the callbacks.. 

but i have come with a completely new way of doing it so i will be testing that on steamtracker2 repo before i commit it here.
